name: "Ahold Yurii content"
on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'type the file name (*.spec.js)'
        required: true         
jobs:
  build:
      runs-on: ubuntu-latest
      
